# Port 8081
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=TODO
spring.datasource.password=todo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Keycloak aktivieren
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/TODO
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/TODO/protocol/openid-connect/certs

# Swagger UI Pfad
springdoc.swagger-ui.path=/swagger-ui.html