# Port 8081 nutzen
server.port=8081

# PostgreSQL (Das funktioniert jetzt!)
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=todo
spring.jpa.hibernate.ddl-auto=update

# Keycloak wieder aktivieren (Die Rauten # entfernen!)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ILV
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ILV/protocol/openid-connect/certs

# Swagger UI Pfad
springdoc.swagger-ui.path=/swagger-ui.html